// <auto-generated />
using System;
using FormBuilder.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormBuilder.Infrastructure.Migrations
{
    [DbContext(typeof(FormBuilderDbContext))]
    [Migration("20260605131704_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("FormBuilder.Domain.Entities.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("FormBuilder.Domain.Entities.FormAnswerDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormAnswerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FormAnswerId");

                    b.HasIndex("FormFieldId");

                    b.ToTable("FormAnswerDetails");
                });

            modelBuilder.Entity("FormBuilder.Domain.Entities.FormAnswers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("FormAnswers");
                });

            modelBuilder.Entity("FormBuilder.Domain.Entities.FormFields", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("FieldType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Placeholder")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("FormFields");
                });

            modelBuilder.Entity("FormBuilder.Domain.Entities.FormAnswerDetail", b =>
                {
                    b.HasOne("FormBuilder.Domain.Entities.FormAnswers", "FormAnswer")
                        .WithMany("AnswerDetails")
                        .HasForeignKey("FormAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormBuilder.Domain.Entities.FormFields", "FormField")
                        .WithMany("AnswerDetails")
                        .HasForeignKey("FormFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormAnswer");

                    b.Navigation("FormField");
                });

            modelBuilder.Entity("FormBuilder.Domain.Entities.FormAnswers", b =>
                {
                    b.HasOne("FormBuilder.Domain.Entities.Form", "Form")
                        .WithMany("Answers")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("FormBuilder.Domain.Entities.FormFields", b =>
                {
                    b.HasOne("FormBuilder.Domain.Entities.Form", "Form")
                        .WithMany("Fields")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("FormBuilder.Domain.Entities.Form", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("FormBuilder.Domain.Entities.FormAnswers", b =>
                {
                    b.Navigation("AnswerDetails");
                });

            modelBuilder.Entity("FormBuilder.Domain.Entities.FormFields", b =>
                {
                    b.Navigation("AnswerDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
